defaults: &defaults
  working_directory: ~/rabbitmq-adaptor-js
  docker:
    - image: circleci/node:10

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}--{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}--{{ checksum "package-lock.json" }}
          paths:
            - node_modules

  static_tests:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}--{{ checksum "package-lock.json" }}
      - run: npm run lint

workflows:
  version: 2
  default:
    jobs:
      - build
      - static_tests:
          requires:
            - build
